<?xml version="0.46"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="megabot">

  <!-- Include files for robot subcomponents -->
  <xacro:include filename="$(find megabot)/urdf/wheel.urdf.xacro" />
  <xacro:include filename="$(find megabot)/urdf/camera.urdf.xacro" />

  <!-- Global constants -->
  <xacro:property name="M_PI" value="3.14159"/>

  <!-- Root link for motion control -->
  <link name="base_footprint">
   <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.001 0.001 0.001" />
      </geometry>
    </visual>
  </link>
  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>

  <!-- Reference link -->
  <link name="base_link">
    <inertial>
      <mass value="50" />
      <origin xyz="0 0 0" />
      <inertia ixx="50.0" ixy="0.0" ixz="0.0"
        iyy="50.0" iyz="0.0"
        izz="50.0" />
    </inertial>
    <collision>
      <origin xyz="0 0 0.01" />
      <geometry>
        <box size="0.2 0.2 0.02" />
      </geometry>
    </collision>
  </link>

  <!-- Robot base plate -->
  <link name="base_plate">
    <inertial>
      <mass value="50" />
      <origin xyz="0 0 0" />
      <inertia ixx="50.0" ixy="0.0" ixz="0.0"
        iyy="50.0" iyz="0.0"
        izz="50.0" />
    </inertial>
    <visual>
      <geometry>
        <box size="0.3 0.25 0.02" />
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="0.3 0.25 0.02" />
      </geometry>
    </collision>
  </link>
  <joint name="base_plate_joint" type="fixed">
    <origin xyz="0 0 0.04" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="base_plate" />
  </joint>

  <!-- Wheel parameters -->
  <xacro:property name="wheelbase" value="0.25" />
  <xacro:property name="track" value="0.3" />
  <xacro:property name="wheel_vertical_offset" value="0.03" />

  <!-- Wheel properties -->
  <xacro:property name="wheel_length" value="0.032" />
  <xacro:property name="wheel_radius" value="0.03" />

  <!-- Add wheels via macros -->
  <xacro:megabot_wheel wheel_prefix="front_left">
    <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:megabot_wheel>
  <xacro:megabot_wheel wheel_prefix="front_right">
    <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:megabot_wheel>
  <xacro:megabot_wheel wheel_prefix="rear_left">
    <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:megabot_wheel>
  <xacro:megabot_wheel wheel_prefix="rear_right">
    <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:megabot_wheel>

  <!-- Camera parameters -->
  <xacro:property name="camera_size" value="0.03" /> <!-- Size of square 'camera' box -->
  <xacro:property name="camera_front_offset" value="0.1" /> <!-- Size of square 'camera' box -->
  <xacro:property name="camera_height" value="0.4" /> <!-- Size of square 'camera' box -->
  <xacro:property name="camera_pitch" value="0.8" /> <!-- Size of square 'camera' box -->

  <!-- Add camera via macros -->
  <xacro:megabot_camera />

  <!-- Set method of motion control in Gazebo -->
  <gazebo>
    <plugin name="object_controller" filename="libgazebo_ros_planar_move.so">
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>map</odometryFrame>
      <odometryRate>10.0</odometryRate>
      <robotBaseFrame>base_footprint</robotBaseFrame>
    </plugin>
  </gazebo>

</robot>

