<?xml version="0.46"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="megabot">

  <!-- Include files for robot subcomponents -->
  <xacro:include filename="$(find megabot)/urdf/wheel.urdf.xacro" />
  <xacro:include filename="$(find megabot)/urdf/camera.urdf.xacro" />
  <xacro:include filename="$(find hector_sensors_description)/urdf/sonar_sensor.urdf.xacro" />

  <!-- Global constants -->
  <xacro:property name="M_PI" value="3.14159"/>

  <!-- Root link for motion control -->
  <link name="base_footprint">
   <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.001 0.001 0.001" />
      </geometry>
    </visual>
  </link>
  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>

  <!-- Reference link -->
  <link name="base_link">
    <inertial>
      <mass value="50" />
      <origin xyz="0 0 0" />
      <inertia ixx="50.0" ixy="0.0" ixz="0.0"
        iyy="50.0" iyz="0.0"
        izz="50.0" />
    </inertial>
    <collision>
      <origin xyz="0 0 0.01" />
      <geometry>
        <box size="0.2 0.2 0.02" />
      </geometry>
    </collision>
  </link>

  <!-- Robot base plate -->
  <link name="base_plate">
    <inertial>
      <mass value="50" />
      <origin xyz="0 0 0" />
      <inertia ixx="50.0" ixy="0.0" ixz="0.0"
        iyy="50.0" iyz="0.0"
        izz="50.0" />
    </inertial>
    <visual>
      <geometry>
        <box size="0.3 0.25 0.02" />
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="0.3 0.25 0.02" />
      </geometry>
    </collision>
  </link>
  <joint name="base_plate_joint" type="fixed">
    <origin xyz="0 0 0.04" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="base_plate" />
  </joint>

  <link name="right_grabber">
    <inertial>
      <mass value="50" />
      <origin xyz="0 0 0" />
      <inertia ixx="50.0" ixy="0.0" ixz="0.0"
        iyy="50.0" iyz="0.0"
        izz="50.0" />
    </inertial>
    <visual>
      <geometry>
        <sphere radius="0.033" />
      </geometry>
    </visual>
  </link>
  <joint name="right_grabber_joint" type="fixed">
    <origin xyz="0.239 -0.067 0.03" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="right_grabber" />
  </joint>

  <link name="left_grabber">
    <inertial>
      <mass value="50" />
      <origin xyz="0 0 0" />
      <inertia ixx="50.0" ixy="0.0" ixz="0.0"
        iyy="50.0" iyz="0.0"
        izz="50.0" />
    </inertial>
    <visual>
      <geometry>
        <sphere radius="0.033" />
      </geometry>
    </visual>
  </link>
  <joint name="left_grabber_joint" type="fixed">
    <origin xyz="0.231 0.039 0.03" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="left_grabber" />
  </joint>

  <!-- Wheel parameters -->
  <xacro:property name="wheelbase" value="0.25" />
  <xacro:property name="track" value="0.3" />
  <xacro:property name="wheel_vertical_offset" value="0.03" />

  <!-- Wheel properties -->
  <xacro:property name="wheel_length" value="0.032" />
  <xacro:property name="wheel_radius" value="0.03" />

  <!-- Add wheels via macros -->
  <xacro:megabot_wheel wheel_prefix="front_left">
    <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:megabot_wheel>
  <xacro:megabot_wheel wheel_prefix="front_right">
    <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:megabot_wheel>
  <xacro:megabot_wheel wheel_prefix="rear_left">
    <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:megabot_wheel>
  <xacro:megabot_wheel wheel_prefix="rear_right">
    <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:megabot_wheel>

  <!-- Camera parameters -->
  <xacro:property name="camera_size" value="0.03" />
  <xacro:property name="camera_front_offset" value="0.185" />
  <xacro:property name="camera_height" value="0.43" />
  <xacro:property name="camera_pitch" value="1.22" />

  <!-- Add camera via macros -->
  <xacro:megabot_camera />

  <xacro:property name="sonar_ur" value="25.0"/>
  <xacro:property name="sonar_min_rng" value="0.1"/>
  <xacro:property name="sonar_max_rng" value="0.8"/>
  <xacro:property name="sonar_fov" value="0.1"/>
  <xacro:property name="sonar_rc" value="5"/>

  <xacro:sonar_sensor name="sonar_front" parent="base_plate" ros_topic="sonar_front" update_rate="${sonar_ur}" min_range="${sonar_min_rng}" max_range="${sonar_max_rng}" field_of_view="${sonar_fov}" ray_count="${sonar_rc}">
    <origin xyz="${wheelbase/2} 0 0" rpy="0 0 0"/>
  </xacro:sonar_sensor>
  <xacro:sonar_sensor name="sonar_left" parent="base_plate" ros_topic="sonar_left" update_rate="${sonar_ur}" min_range="${sonar_min_rng}" max_range="${sonar_max_rng}" field_of_view="${sonar_fov}" ray_count="${sonar_rc}">
    <origin xyz="0 ${track/2} 0" rpy="0 0 ${M_PI/2}"/>
  </xacro:sonar_sensor>
  <xacro:sonar_sensor name="sonar_right" parent="base_plate" ros_topic="sonar_right" update_rate="${sonar_ur}" min_range="${sonar_min_rng}" max_range="${sonar_max_rng}" field_of_view="${sonar_fov}" ray_count="${sonar_rc}">
    <origin xyz="0 -${track/2} 0" rpy="0 0 -${M_PI/2}"/>
  </xacro:sonar_sensor>
  <xacro:sonar_sensor name="sonar_back" parent="base_plate" ros_topic="sonar_back" update_rate="${sonar_ur}" min_range="${sonar_min_rng}" max_range="${sonar_max_rng}" field_of_view="${sonar_fov}" ray_count="${sonar_rc}">
    <origin xyz="-${wheelbase/2} 0 0" rpy="0 0 ${M_PI}"/>
  </xacro:sonar_sensor>

  <!-- Set method of motion control in Gazebo -->
  <gazebo>
    <plugin name="object_controller" filename="libgazebo_ros_planar_move.so">
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <odometryRate>10.0</odometryRate>
      <robotBaseFrame>base_footprint</robotBaseFrame>
    </plugin>

    <plugin name="magnetometer" filename="libhector_gazebo_ros_magnetic.so">
      <updateRate>20.0</updateRate>
      <robotNamespace>megabot</robotNamespace>
      <bodyName>base_footprint</bodyName>
      <drift>0 0 0</drift>
      <driftFrequency>0 0 0</driftFrequency>
      <gaussianNoise>0 0 0</gaussianNoise>
      <!-- <referenceHeading>0.0</referenceHeading> -->
      <!-- <declination>0</declination> -->
      <!-- <inclination>0</inclination> -->
      <!-- <offset>0 0 0</offset> -->
    </plugin>
  </gazebo>
</robot>

