#!/usr/bin/env python

import rospy
import smach_ros
from smach import StateMachine
from state_functions import *

def main():
    rospy.init_node('master_state_machine')

    sm = StateMachine(outcomes=["succeeded", "preempted", "aborted"])

    with sm:
        StateMachine.add("RESET_ROBOT", build_reset_state(), {"succeeded": "BUCKET_DROP"})
        StateMachine.add("BUCKET_DROP", build_bucket_drop_state(), {"succeeded": "BUCKET_DROP"})

    introspection_server = smach_ros.IntrospectionServer('smach_server', sm, '/SM_ROOT')
    introspection_server.start()
    sm.execute()
    introspection_server.stop()

if __name__ == "__main__":
    main()
