#!/usr/bin/env python

import rospy
import smach_ros
from smach import StateMachine, Concurrence
from state_functions import *

def main():
    rospy.init_node('master_state_machine')

    sm = StateMachine(outcomes=["succeeded", "preempted", "aborted"])

    with sm:
        StateMachine.add("RESET_ROBOT", build_reset_state(),
                                {"succeeded": "LOAD_INITIAL_BALL"})
        StateMachine.add("LOAD_INITIAL_BALL", build_load_initial_ball_state(),
                                {"succeeded": "PICKUP_LEFT_BALL"})
        StateMachine.add("PICKUP_LEFT_BALL", build_pickup_left_ball_state(),
                                {"succeeded": "PICKUP_MIDDLE_RIGHT_BALLS"})
        StateMachine.add("PICKUP_MIDDLE_RIGHT_BALLS", build_pickup_middle_right_balls_state(),
                                {"succeeded": "succeeded"})
        # StateMachine.add("PICKUP_AREA_BALLS", build_pickup_area_balls_state())

    introspection_server = smach_ros.IntrospectionServer('smach_server', sm, '/SM_ROOT')
    introspection_server.start()
    sm.execute()
    introspection_server.stop()

def build_load_initial_ball_state():
    sm = StateMachine(outcomes=["succeeded", "preempted", "aborted"])

    grabber_frame = "right_grabber"
    distance_limit = 0.02

    with sm:
        StateMachine.add("DETECT_CLOSEST_BALL", closest_ball(grabber_frame, distance_limit),
            {"succeeded": "CLOSE_GRABBER", "aborted": "DETECT_CLOSEST_BALL"},
            remapping={"position": "ball_location"})
        StateMachine.add("CLOSE_GRABBER", grab(grabber_frame), {"succeeded": "succeeded"})
    return sm

def build_pickup_left_ball_state():
    sm = StateMachine(outcomes = ["succeeded", "preempted", "aborted"])

    with sm:
        StateMachine.add("DRIVE_START_FORWARD", drive_pose(1.2, 0.73, 133, 0.2, 15), {"succeeded": "DRIVE_LEFT_FIELD"})
        StateMachine.add("DRIVE_LEFT_FIELD", drive_pose(1.04, 0.95, 133, 0.1, 5), {"succeeded": "GRAB_BALL"})
        StateMachine.add("GRAB_BALL", build_pickup_state("left_grabber", 0.4), {"succeeded": "LINE_FRONT_FIELD"})
        StateMachine.add("LINE_FRONT_FIELD", drive_pose(1.04, 0.95, 133, 0.1, 5), {"succeeded": "DELAY"})
        StateMachine.add("DELAY", Delay(1), {"succeeded": "DROP_BUCKET"})
        StateMachine.add("DROP_BUCKET", build_bucket_drop_state())
    return sm

def build_pickup_middle_right_balls_state():
    sm = StateMachine(outcomes = ["succeeded", "preempted", "aborted"])

    with sm:
        StateMachine.add("DRIVE_MIDDLE_FIELD", drive_pose(1.2, 1.6, -90, 0.01, 1), {"succeeded": "GRAB_BALL_MIDDLE"})
        StateMachine.add("GRAB_BALL_MIDDLE", build_pickup_state("right_grabber", 9999), {"succeeded": "DRIVE_MIDDLE_FIELD_2"})
        StateMachine.add("DRIVE_MIDDLE_FIELD_2", drive_pose(1.2, 1.6, -90, 0.01, 1), {"succeeded": "DRIVE_RIGHT_FIELD"})
        StateMachine.add("DRIVE_RIGHT_FIELD", drive_pose(1.7, 1.6, -90, 0.01, 1), {"succeeded": "GRAB_BALL_RIGHT"})
        StateMachine.add("GRAB_BALL_RIGHT", build_pickup_state("left_grabber", 9999), {"succeeded": "DROP_BUCKET"})
        StateMachine.add("DROP_BUCKET", build_bucket_drop_state())
    return sm

def build_pickup_area_balls_state():
    sm = StateMachine(outcomes = ["succeeded", "preempted", "aborted"])

    with sm:
        StateMachine.add("DRIVE_MIDDLE_FIELD", drive_point(1.7, 1.2, 0.01), {"succeeded": "DRIVE_LEFT_FIELD"})
        StateMachine.add("DRIVE_LEFT_FIELD", drive_point(0.3, 1.0, 0.01), {"succeeded": "DRIVE_BALL_PIT_FIELD_RIGHT"})
        StateMachine.add("DRIVE_BALL_PIT_FIELD_RIGHT", drive_point(0.3, 0.7, 0.01), {"succeeded": "GRAB_BALL_RIGHT"})
        StateMachine.add("GRAB_BALL_RIGHT", build_pickup_state("right_grabber", 9999), {"succeeded": "DRIVE_BALL_PIT_FIELD_LEFT"})
        StateMachine.add("DRIVE_BALL_PIT_FIELD_LEFT", drive_point(0.3, 0.7, 0.01), {"succeeded": "GRAB_BALL_LEFT"})
        StateMachine.add("GRAB_BALL_LEFT", build_pickup_state("left_grabber", 9999), {"succeeded": "DRIVE_LEFT_BUCKET_FIELD"})
        StateMachine.add("DRIVE_LEFT_BUCKET_FIELD", drive_point(0.1, 1.8, 0.01), {"succeeded": "LIFT_LIFTER"})
        StateMachine.add("LIFT_LIFTER", lift(), {"succeeded": "DRIVE_LEFT_BUCKET"})
        StateMachine.add("DRIVE_LEFT_BUCKET", drive_point(0.1, 2.0, 0.01), {"succeeded": "OPEN_LEFT_GRABBER"})
        StateMachine.add("OPEN_LEFT_GRABBER", release("left_grabber"), {"succeeded": "OPEN_RIGHT_GRABBER"})
        StateMachine.add("OPEN_RIGHT_GRABBER", release("right_grabber"), {"succeeded": "DRIVE_LEFT_BUCKET_LOWER"})
        StateMachine.add("DRIVE_LEFT_BUCKET_LOWER", drive_point(0.1, 1.8, 0.01), {"succeeded": "LOWER_LIFTER"})
        StateMachine.add("LOWER_LIFTER", lower())
    
    return sm

if __name__ == "__main__":
    main()
