#!/usr/bin/env python

import rospy
import smach_ros
from smach import StateMachine
from state_functions import *

def main():
    rospy.init_node('master_state_machine')

    sm = StateMachine(outcomes=["succeeded", "preempted", "aborted"])

    with sm:
        StateMachine.add("RESET_ROBOT", build_reset_state(), {"succeeded": "LINE"})
        StateMachine.add("LINE", drive_pose(0.7, 1.6, -90, 0.01, 1), {"succeeded": "DELAY1"})
        StateMachine.add("DELAY1", Delay(1), {"succeeded": "TEST"})
        StateMachine.add("TEST", drive_pose(0.9, 1.8, 0, 0.01, 1), {"succeeded": "DELAY2"})
        StateMachine.add("DELAY2", Delay(1), {"succeeded": "LINE"})

    introspection_server = smach_ros.IntrospectionServer('smach_server', sm, '/SM_ROOT')
    introspection_server.start()
    sm.execute()
    introspection_server.stop()

if __name__ == "__main__":
    main()
